Factory/Models/EngMach.cs
namespace Factory.Models
{
  public class EngMach
    {       
        public int EngMachId { get; set; }
        public int EngineerId { get; set; }
        public Engineer Engineer { get; set; }
        public int MachineId { get; set; }
        public Machine Machine { get; set; }
    }
}

Factory/Models/Engineer.cs
using System.Collections.Generic;
using System;
using System.ComponentModel.DataAnnotations;

namespace Factory.Models
{
  public class Engineer
  {
    public int EngineerId { get; set; }
    [Required(ErrorMessage = "The Engineer's Name field can't be empty!")]
    public string EngineerName { get; set; }
    
    [Required(ErrorMessage = "The Engineer's Hire Date field can't be empty!")]
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:M/d/yyyy}")]
    public DateTime HireDate { get; set; }
    public List<EngMach> JoinEntities { get; }
  }
}

Factory/Models/FactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models
{
  public class FactoryContext : DbContext
  {
    public DbSet<Engineer> Engineers { get; set; }
    public DbSet<Machine> Machines { get; set; }
    public DbSet<EngMach> EngMachs { get; set; }

    public FactoryContext(DbContextOptions options) : base(options) { }
  }
}

Factory/Models/Machine.cs
using System.Collections.Generic;
using System;
using System.ComponentModel.DataAnnotations;

namespace Factory.Models
{
  public class Machine
  {
    public int MachineId { get; set; }

    [Required(ErrorMessage = "The Machine's Name field can't be empty!")]
    public string MachineName { get; set; }

    [Required(ErrorMessage = "The Machine's Install Date field can't be empty!")]
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:M/d/yyyy}")]
    public DateTime InstallDate { get; set; }

    public List<EngMach> JoinEntities { get; }
  }
}

Factory/Controllers/EngineerController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;
    public EngineersController(FactoryContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Engineer> model = _db.Engineers
                            .ToList();
      return View(model);
    }
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer)
    {
      if (!ModelState.IsValid)
      {
        return View(engineer);
      }
      else
      {
        _db.Engineers.Add(engineer);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public ActionResult Details(int id)
    {
      Engineer thisEngineer = _db.Engineers
          .Include(engineer => engineer.JoinEntities)
          .ThenInclude(join => join.Machine)
          .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Edit(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineers => engineers.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer)
    {
      _db.Engineers.Update(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(Engineers => Engineers.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(Engineers => Engineers.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddMachine(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int machineId)
    {
#nullable enable
      EngMach? joinEntity = _db.EngMachs.FirstOrDefault(join => (join.MachineId == machineId && join.EngineerId == engineer.EngineerId));
#nullable disable
      if (joinEntity == null && machineId != 0)
      {
        _db.EngMachs.Add(new EngMach() { MachineId = machineId, EngineerId = engineer.EngineerId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = engineer.EngineerId });
    }
        [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      EngMach joinEntry = _db.EngMachs.FirstOrDefault(entry => entry.EngMachId == joinId);
      _db.EngMachs.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Controllers/HomeController.cs
using Factory.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Factory.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

Factory/Controllers/MachineController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;
    public MachinesController(FactoryContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Machine> model = _db.Machines
                            .ToList();
      return View(model);
    }
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine)
    {
      if (!ModelState.IsValid)
      {
        return View(machine);
      }
      else
      {
        _db.Machines.Add(machine);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }
    public ActionResult Details(int id)
    {
      Machine thisMachine = _db.Machines
          .Include(machine => machine.JoinEntities)
          .ThenInclude(join => join.Engineer)
          .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }
    public ActionResult Edit(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machines => machines.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine)
    {
      _db.Machines.Update(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machines => machines.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machines => machines.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddEngineer(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "EngineerName");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int engineerId)
    {
#nullable enable
      EngMach? joinEntity = _db.EngMachs.FirstOrDefault(join => (join.EngineerId == engineerId && join.MachineId == machine.MachineId));
#nullable disable
      if (joinEntity == null && engineerId != 0)
      {
        _db.EngMachs.Add(new EngMach() { EngineerId = engineerId, MachineId = machine.MachineId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = machine.MachineId });
    }
        public ActionResult DeleteJoin(int joinId)
    {
      EngMach joinEntry = _db.EngMachs.FirstOrDefault(entry => entry.EngMachId == joinId);
      _db.EngMachs.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Add a Machine</h2>

<h4>Add a Machine to this Engineer: @Html.DisplayFor(model => model.EngineerName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.EngineerId)

    @Html.Label("Select a Machine")
    @Html.DropDownList("MachineId")

    <input type="submit" value="Save" />
}
<hr>
<p>@Html.ActionLink("Back to list of Engineers", "Index") |
@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h4>Add a new Engineer</h4>
<p>@Html.ValidationMessageFor(model => model.EngineerName, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>
<p>@Html.ValidationMessageFor(model => model.HireDate, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.EngineerName, "Engineer Name: ")
  @Html.TextBoxFor(model => model.EngineerName)

  @Html.LabelFor(model => model.HireDate, "Hire Date: ")
  @Html.EditorFor(model => model.HireDate)


  <input type="submit" value="Add new Engineer"/>
}
<hr>
<p>
  @Html.ActionLink("Show all Engineers", "Index") |
  @Html.ActionLink("Return Home", "Index", "Home")
</p>

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Are you sure you want to delete this Engineer?</h2>

@Html.LabelFor(model => model.EngineerName, "Engineer Name: ") @Html.DisplayFor(model => model.EngineerName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
<hr>
<p>
  @Html.ActionLink("Back to list of Engineers", "Index") |
  @Html.ActionLink("Back Home", "Index", "Home")
</p>

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models
@model Factory.Models.Engineer

<h2>Engineer Details</h2>
<hr />
<h3>@Html.LabelFor(model => model.EngineerName, "Engineer Name: ") @Html.DisplayFor(model => model.EngineerName)</h3>  
<h3>@Html.LabelFor(model => model.HireDate, "Date Hired: ") @Html.DisplayFor(model => model.HireDate)</h3>  


@if(@Model.JoinEntities.Count == 0)
{
  <p>This Engineer is not licensed for any Machines yet!</p>
}
else
{
  <h4>This Engineer is licensed for the following Machines:</h4>
  <ul>
    @foreach(EngMach join in Model.JoinEntities)
    {
      <li>Machine: @join.Machine.MachineName</li>
      @using (Html.BeginForm("DeleteJoin", "Engineers"))
{
  @Html.Hidden("joinId", @join.EngMachId)
  <input type="submit" value="Delete"/>
}
    }
  </ul>
}



<p>
  @Html.ActionLink("Add a Machine", "AddMachine", new { id = Model.EngineerId }) | 
  @Html.ActionLink("Edit", "Edit", new { id = Model.EngineerId }) | 
  @Html.ActionLink("Delete", "Delete", new { id = Model.EngineerId }) | 
  <hr>
  <br>
  @Html.ActionLink("Back to the list of Engineers", "Index") | 
  @Html.ActionLink("Return Home", "Index", "Home")
</p>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Edit</h2>

<h4>Edit this Engineer: @Html.DisplayFor(model => model.EngineerName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.LabelFor(model => model.EngineerName, "Engineer Name: ")
  @Html.EditorFor(model => model.EngineerName)

  @Html.LabelFor(model => model.HireDate, "Hire Date: ")
  @Html.EditorFor(model => model.HireDate)

  <input type="submit" value="Save" />
}
<hr>
<p>
  @Html.ActionLink("Back to list of Engineers", "Index") |
  @Html.ActionLink("Return Home", "Index", "Home")
</p>

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;

<h1>Engineers</h1>

@if (@Model.Count == 0)
{
  <h3>No Engineers have been added yet!</h3>
} 
else
{
  <ul>
    @foreach (Engineer engineer in Model)
    {
      <br>
      <li>@Html.ActionLink($"{engineer.EngineerName}", "Details", new { id = engineer.EngineerId })</li>
    }
  </ul>
}
<hr>
<p>@Html.ActionLink("Add a new engineer", "Create") |
@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}
<h1>Hello, Factory Manager</h1>
<h1>Welcome to Dr. Sillystringz's Factory</h1>
<hr>
<p>
  @Html.ActionLink("See all Engineers", "Index", "Engineers") | 
  @Html.ActionLink("See all Machines", "Index", "Machines")
</p>

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Add an Engineer</h2>

<h4>Add an Engineer to this Machine: @Html.DisplayFor(model => model.MachineName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.MachineId)

    @Html.Label("Select an Engineer")
    @Html.DropDownList("EngineerId")

    <input type="submit" value="Save" />
}
<hr>
<p>
  @Html.ActionLink("Back to list of Machines", "Index") |
  @Html.ActionLink("Home", "Index", "Home")
</p>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h4>Add a new Machine</h4>
<p>@Html.ValidationMessageFor(model => model.MachineName, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>
<p>@Html.ValidationMessageFor(model => model.InstallDate, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.MachineName, "Machine Name: ")
  @Html.TextBoxFor(model => model.MachineName)

  @Html.LabelFor(model => model.InstallDate, "Install Date: ")
  @Html.EditorFor(model => model.InstallDate)


  <input type="submit" value="Add new Machine"/>
}
<hr>
<p>
  @Html.ActionLink("Show all Machines", "Index") | 
  @Html.ActionLink("Return Home", "Index", "Home")
</p>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Are you sure you want to delete this Machine?</h2>

@Html.LabelFor(model => model.MachineName, "Machine Name: ") @Html.DisplayFor(model => model.MachineName)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
<hr>
<p>
  @Html.ActionLink("Back to list of Machines", "Index") |
  @Html.ActionLink("Back Home", "Index", "Home")
</p>

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models
@model Factory.Models.Machine

<h2>Machine Details</h2>
<hr />
<h3>@Html.LabelFor(model => model.MachineName, "Machine Name: ") @Html.DisplayFor(model => model.MachineName)</h3>
<h3>@Html.LabelFor(model => model.InstallDate, "Install Date: ") @Html.DisplayFor(model => model.InstallDate)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>There are no Engineers licensed for this Machine.</p>
}
else
{
  <h4>Engineers licensed for this Machine:</h4>
  <ul>
  @foreach(EngMach join in Model.JoinEntities)
  {
    <li>@join.Engineer.EngineerName</li>
    <li>@join.Engineer.HireDate</li>

@using (Html.BeginForm("DeleteJoin", "Machines"))
{
  @Html.Hidden("joinId", @join.EngMachId)
  <input type="submit" value="Delete"/>
}
  }
  </ul>
}


<p>
  @Html.ActionLink("Add an Engineer", "AddEngineer", new { id = Model.MachineId }) |
  @Html.ActionLink("Edit", "Edit", new { id = Model.MachineId }) |
  @Html.ActionLink("Delete", "Delete", new { id = Model.MachineId })
  <hr>
  <br>
  @Html.ActionLink("Back to the list of Machines", "Index") |
  @Html.ActionLink("Back Home", "Index", "Home")
</p>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Edit</h2>

<h4>Edit this Machine: @Html.DisplayFor(model => model.MachineName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.LabelFor(model => model.MachineName, "Machine Name: ")
  @Html.EditorFor(model => model.MachineName)

  @Html.LabelFor(model => model.InstallDate, "Install Date: ")
  @Html.EditorFor(model => model.InstallDate)

  <input type="submit" value="Save" />
}
<hr>
<p>
  @Html.ActionLink("Back to list of Machines", "Index") |
  @Html.ActionLink("Return Home", "Index", "Home")
</p>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;

<h1>Machines</h1>

@if (@Model.Count == 0)
{
  <h3>No Machines have been added yet!</h3>
} 
else
{
  <ul>
    @foreach (Machine machine in Model)
    {
      <br>
      <li>@Html.ActionLink($"{machine.MachineName}", "Details", new { id = machine.MachineId })</li>
    }
  </ul>
}
<hr>
<p>
  @Html.ActionLink("Add a new Machine", "Create") | 
  @Html.ActionLink("Home", "Index", "Home")
</p>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Dr. Sillystringz's Factory</title>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>